### ISSUE TITLE
Sign in request failed, unable to register

### ISSUE THREAD

**Issue by shaunhurryup** [earlyai/earlyai-vscode-release#10]
![CleanShot 2024-11-12 at 16 52 31@2x](https://github.com/user-attachments/assets/ffa90847-0b06-461c-b92e-5cf5af2c27d6)

**Comment by liorf1** [comment]
Hi @shaunhurryup, 

Thank you for bringing this to our attention, and I sincerely apologize for the delay in addressing your issue.

Since your last attempt, we’ve updated our authentication system to use Single Sign-On (SSO) with Google and GitHub for improved security and convenience. We recommend trying to sign in again using either your Google or GitHub account.

If you encounter any issues or have further questions, please don’t hesitate to let us know. We truly appreciate your patience and understanding.

Best regards,
EarlyAI Support Team
